#!/bin/sh

expr="`date +%N` % 7"
case `echo $expr | bc` in
    0)
        op="extend"
        ;;
    1)
        op="join"
        ;;
    2)
        op="minus"
        ;;
    3)
        op="project"
        ;;
    4)
        op="select"
        ;;
    5)
        op="summary"
        ;;
    6)
        op="union"
        ;;
esac

echo "<div style='text-transform:capitalize;font-weight:bold;'>$op:</div>"

echo "<div style='border:1px solid #e7e7e8;'>"
echo "<img src='diagram-$op.png' alt='$op operator'/>"
echo "</div>"

echo "<div style='text-align:right'>Get the full Bandicoot "
echo "algebra <a href='bandicoot-algebra.pdf'>PDF</a> (100KB).</div>"
